title: Dive with Na
author: Na
email: na@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  To dive or not to dive? Is it a real question that wakes you up at night? Try your virtual dive experince with Na and decide after. 

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
